# Generated by Django 3.2.7 on 2021-11-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='release_date',
            field=models.DateField(verbose_name='date released'),
        ),
    ]
