# Generated by Django 3.2.7 on 2021-11-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_console_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='release_date',
            field=models.DateTimeField(verbose_name='date released'),
        ),
    ]
