# Generated by Django 3.2.7 on 2021-11-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_console_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='release_date',
            field=models.DateField(verbose_name='date released'),
        ),
    ]
